project:
  type: website
  output-dir: ./docs/

website:
  title: "Polar documentation"
  navbar:
    title: false
    background: primary
    search: true
    left:
      - text: Home
        href: https://germanogallicchio.github.io/index.html
      - text: Software
        href: https://germanogallicchio.github.io/software.html
      - text: Polar docs
        href: index.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
